# fly.toml app configuration file generated for kindly-dedup-stripe on 2025-11-10T17:57:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kindly-dedup-stripe'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_PORT = '3000'
  RUST_LOG = 'info'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.http_checks]]
    interval = '10s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
