use crate::strategic_map::{StrategicEventKind, StrategicEventSnapshot, StrategicMapCapsule};
use atomic_capsule::verify_alignment_only;
use core::hash::{Hash, Hasher};
use core::sync::atomic::{AtomicU64, Ordering};

/// Type of economic order (extendable later for production/manpower).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuildOrderKind {
    Infrastructure = 0,
}

impl BuildOrderKind {
    pub fn as_u8(self) -> u8 {
        self as u8
    }

    pub fn from_u8(raw: u8) -> Option<Self> {
        match raw {
            0 => Some(Self::Infrastructure),
            _ => None,
        }
    }
}

/// Snapshot of a queued build order.
#[derive(Debug, Clone)]
pub struct BuildOrderSnapshot {
    pub province_id: u32,
    pub kind: BuildOrderKind,
    pub target_infra_q16: u32,
    pub remaining_ticks: u32,
    pub generation: u64,
}

/// Immutable snapshot of the economy capsule.
#[derive(Debug, Clone)]
pub struct EconomySnapshot {
    pub tick: u64,
    pub generation: u64,
    pub hash_chain: u64,
    pub prev_hash_chain: u64,
    pub orders: Vec<BuildOrderSnapshot>,
}

#[derive(Debug, Clone)]
struct BuildOrder {
    province_id: u32,
    kind: BuildOrderKind,
    target_infra_q16: u32,
    remaining_ticks: u32,
    generation: u64,
}

/// Province economy capsule (batch tick, cache-aligned, generation-tracked).
#[repr(C, align(128))]
pub struct ProvinceEconomyCapsule {
    orders: Vec<BuildOrder>,
    generation: AtomicU64,
    hash_chain: AtomicU64,
    last_tick: AtomicU64,
    _padding: [u8; 88],
}

verify_alignment_only!(ProvinceEconomyCapsule, 128);

impl ProvinceEconomyCapsule {
    pub fn new() -> Self {
        Self {
            orders: Vec::new(),
            generation: AtomicU64::new(1),
            hash_chain: AtomicU64::new(0),
            last_tick: AtomicU64::new(0),
            _padding: [0; 88],
        }
    }

    /// Queue an infrastructure repair/upgrade (deterministic order).
    pub fn enqueue_infrastructure(
        &mut self,
        province_id: u32,
        target_infra_q16: u32,
        duration_ticks: u32,
    ) {
        let gen = self.generation.fetch_add(1, Ordering::AcqRel) + 1;
        self.orders.push(BuildOrder {
            province_id,
            kind: BuildOrderKind::Infrastructure,
            target_infra_q16: target_infra_q16.min(65_536),
            remaining_ticks: duration_ticks.max(1),
            generation: gen,
        });
    }

    /// Batch tick: advances build queues and applies completed infrastructure upgrades into the strategic map.
    /// Returns any StrategicEventSnapshots generated by completed upgrades.
    pub fn tick(
        &mut self,
        tick: u64,
        map: &mut StrategicMapCapsule,
    ) -> Vec<StrategicEventSnapshot> {
        self.last_tick.store(tick, Ordering::Release);
        let mut events = Vec::new();
        for order in self.orders.iter_mut() {
            if order.remaining_ticks > 0 {
                order.remaining_ticks = order.remaining_ticks.saturating_sub(1);
            }
            if order.remaining_ticks == 0 {
                match order.kind {
                    BuildOrderKind::Infrastructure => {
                        if let Some(prov) = map.provinces_mut().get_mut(order.province_id as usize) {
                            let prev = prov.infrastructure_q16().min(65_536);
                            let target = order.target_infra_q16.max(prev);
                            if target > prev {
                                prov.set_infrastructure(target);
                                events.push(StrategicEventSnapshot {
                                    kind: StrategicEventKind::InfrastructureRepair,
                                    province_id: order.province_id,
                                    from_owner_id: prov.owner_id(),
                                    to_owner_id: prov.owner_id(),
                                    from_infra_q16: prev,
                                    to_infra_q16: target,
                                    resistance_q16: prov.resistance_q16(),
                                    generation: prov.generation(),
                                });
                            }
                        }
                    }
                }
            }
        }
        self.orders.retain(|o| o.remaining_ticks > 0);
        self.update_hash_chain(tick);
        events
    }

    pub fn snapshot(&self, tick: u64) -> EconomySnapshot {
        let mut orders = Vec::with_capacity(self.orders.len());
        for o in &self.orders {
            orders.push(BuildOrderSnapshot {
                province_id: o.province_id,
                kind: o.kind,
                target_infra_q16: o.target_infra_q16,
                remaining_ticks: o.remaining_ticks,
                generation: o.generation,
            });
        }
        let prev_hash = self.hash_chain.load(Ordering::Acquire);
        let hash = self.compute_hash(tick, &orders, prev_hash);
        self.hash_chain.store(hash, Ordering::Release);
        EconomySnapshot {
            tick,
            generation: self.generation.load(Ordering::Acquire),
            hash_chain: hash,
            prev_hash_chain: prev_hash,
            orders,
        }
    }

    fn update_hash_chain(&self, tick: u64) {
        let prev = self.hash_chain.load(Ordering::Acquire);
        let hash = self.compute_hash(tick, &self.orders_as_snap(), prev);
        self.hash_chain.store(hash, Ordering::Release);
    }

    fn orders_as_snap(&self) -> Vec<BuildOrderSnapshot> {
        self.orders
            .iter()
            .map(|o| BuildOrderSnapshot {
                province_id: o.province_id,
                kind: o.kind,
                target_infra_q16: o.target_infra_q16,
                remaining_ticks: o.remaining_ticks,
                generation: o.generation,
            })
            .collect()
    }

    fn compute_hash(
        &self,
        tick: u64,
        orders: &[BuildOrderSnapshot],
        prev: u64,
    ) -> u64 {
        let mut hasher = fnv::FnvHasher::with_key(prev);
        tick.hash(&mut hasher);
        orders.len().hash(&mut hasher);
        for o in orders.iter().take(8) {
            o.province_id.hash(&mut hasher);
            o.target_infra_q16.hash(&mut hasher);
            o.remaining_ticks.hash(&mut hasher);
            o.kind.as_u8().hash(&mut hasher);
            o.generation.hash(&mut hasher);
        }
        hasher.finish()
    }
}

// Minimal FNV hasher (u64 seed) for hash-chaining snapshots.
mod fnv {
    use core::hash::Hasher;

    pub struct FnvHasher {
        hash: u64,
    }

    impl FnvHasher {
        pub const fn with_key(key: u64) -> Self {
            Self {
                hash: key ^ 0xCBF2_9CE4_8422_2325,
            }
        }
    }

    impl Hasher for FnvHasher {
        fn write(&mut self, bytes: &[u8]) {
            let mut hash = self.hash;
            for &b in bytes {
                hash ^= b as u64;
                hash = hash.wrapping_mul(0x100_0000_01B3);
            }
            self.hash = hash;
        }

        fn finish(&self) -> u64 {
            self.hash
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::strategic_map::ProvinceCapsule;

    #[test]
    fn queue_and_complete_infrastructure_upgrade() {
        let mut map = StrategicMapCapsule::new(vec![ProvinceCapsule::new(0, 50_000, 20_000)], None, None);
        let mut econ = ProvinceEconomyCapsule::new();
        econ.enqueue_infrastructure(0, 30_000, 2);
        let events1 = econ.tick(1, &mut map);
        assert!(events1.is_empty());
        let events2 = econ.tick(2, &mut map);
        assert_eq!(events2.len(), 1);
        assert_eq!(events2[0].kind, StrategicEventKind::InfrastructureRepair);
        let snap = map.step(3);
        assert_eq!(snap.provinces[0].infrastructure_q16, 30_000);
    }

    #[test]
    fn snapshot_hash_changes_on_progress() {
        let mut econ = ProvinceEconomyCapsule::new();
        econ.enqueue_infrastructure(0, 25_000, 3);
        let snap1 = econ.snapshot(1);
        let mut map = StrategicMapCapsule::new(vec![ProvinceCapsule::new(0, 50_000, 20_000)], None, None);
        let _ = econ.tick(2, &mut map);
        let prev_chain = econ.hash_chain.load(Ordering::Acquire);
        let snap2 = econ.snapshot(2);
        assert_ne!(snap1.hash_chain, snap2.hash_chain);
        assert_eq!(snap2.prev_hash_chain, prev_chain);
    }
}
