//! KindlyDB Client - Async HTTP client for KindlyDB user storage
//!
//! Connects to KindlyDB at kindly-hub:8080 for user and audit storage.
//!
//! # Q34 Audit Compliance
//!
//! All audit entries are hash-chained using BLAKE3 for tamper detection.
//! The `prev_hash` field links each entry to the previous one, creating
//! an immutable audit trail.
//!
//! # Example
//!
//! ```rust,ignore
//! use kdb_signup::db::KindlyDbClient;
//!
//! let client = KindlyDbClient::from_env()?;
//! let user = client.get_user_by_email_hash(email_hash).await?;
//! ```

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::env;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use thiserror::Error;
use tokio::sync::RwLock;

// ============================================================================
// Error Types
// ============================================================================

/// Database operation errors
#[derive(Debug, Error)]
pub enum DbError {
    /// Connection to KindlyDB failed
    #[error("Connection failed: {0}")]
    ConnectionFailed(String),

    /// User not found
    #[error("User not found")]
    NotFound,

    /// User already exists (duplicate email_hash)
    #[error("User already exists")]
    AlreadyExists,

    /// Generic database error
    #[error("Database error: {0}")]
    DatabaseError(String),

    /// Missing KINDLYDB_URL environment variable
    #[error("Missing KINDLYDB_URL environment variable")]
    MissingUrl,
}

impl From<reqwest::Error> for DbError {
    fn from(err: reqwest::Error) -> Self {
        DbError::ConnectionFailed(err.to_string())
    }
}

// ============================================================================
// Data Structures
// ============================================================================

/// User record stored in KindlyDB
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    /// Unique user ID (auto-generated by KindlyDB)
    pub id: u64,

    /// BLAKE3 hash of email (indexed for fast lookup)
    pub email_hash: u64,

    /// Encrypted email for sending verification/license emails
    pub email_encrypted: String,

    /// Whether email has been verified
    pub email_verified: bool,

    /// Verification token (6-digit code)
    pub verification_token: Option<String>,

    /// Token expiration timestamp (Unix epoch seconds)
    pub verification_expires_at: Option<u64>,

    /// User tier: 0=Hobby, 1=Pro, 2=Enterprise
    pub tier: u8,

    /// License key (issued after verification)
    pub license_key: Option<String>,

    /// Organization name
    pub org_name: String,

    /// Whether license was issued during promotional period
    pub is_promo: bool,

    /// Creation timestamp (Unix epoch seconds)
    pub created_at: u64,

    /// Last update timestamp (Unix epoch seconds)
    pub updated_at: u64,
}

/// Audit entry for Q34 compliance
///
/// Each entry is hash-chained to the previous via `prev_hash`,
/// creating a tamper-evident audit trail.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignupAuditEntry {
    /// Unique entry ID
    pub id: u64,

    /// Associated user ID
    pub user_id: u64,

    /// Event type: SIGNUP, VERIFIED, LICENSE_ISSUED, RESEND
    pub event_type: String,

    /// Client IP address
    pub ip_address: String,

    /// BLAKE3 hash linking to previous entry (Q34 chain)
    pub prev_hash: u64,

    /// Event timestamp (Unix epoch seconds)
    pub timestamp: u64,
}

/// Response from create user endpoint
#[derive(Debug, Deserialize)]
struct CreateUserResponse {
    id: u64,
}

// ============================================================================
// Hash Chain (Q34 Compliance)
// ============================================================================

/// Compute BLAKE3 hash for audit chain integrity
///
/// The hash includes all entry fields plus the previous hash,
/// creating an immutable chain that detects any tampering.
pub fn compute_audit_hash(entry: &SignupAuditEntry, prev_hash: u64) -> u64 {
    let data = format!(
        "{}:{}:{}:{}:{}",
        entry.user_id, entry.event_type, entry.ip_address, entry.timestamp, prev_hash
    );
    let hash = blake3::hash(data.as_bytes());
    u64::from_le_bytes(
        hash.as_bytes()[..8]
            .try_into()
            .expect("BLAKE3 always produces 32 bytes"),
    )
}

// ============================================================================
// KindlyDB Client
// ============================================================================

/// Async HTTP client for KindlyDB
///
/// Provides user storage and Q34-compliant audit logging.
///
/// # Connection
///
/// Connects to KindlyDB at the URL specified by `KINDLYDB_URL` environment
/// variable, or manually via `KindlyDbClient::new()`.
///
/// # Endpoints
///
/// - `POST /users` - Create user
/// - `GET /users?email_hash={hash}` - Find by email hash
/// - `GET /users/{id}` - Get by ID
/// - `PUT /users/{id}` - Update user
/// - `POST /audit` - Log audit entry
/// - `GET /audit?user_id={id}` - Get audit trail
#[derive(Clone)]
pub struct KindlyDbClient {
    base_url: String,
    client: reqwest::Client,
}

impl KindlyDbClient {
    /// Create a new KindlyDB client with explicit URL
    ///
    /// # Arguments
    ///
    /// * `base_url` - KindlyDB base URL (e.g., "http://kindly-hub:8080")
    pub fn new(base_url: &str) -> Self {
        Self {
            base_url: base_url.trim_end_matches('/').to_string(),
            client: reqwest::Client::new(),
        }
    }

    /// Create client from KINDLYDB_URL environment variable
    ///
    /// # Errors
    ///
    /// Returns `DbError::MissingUrl` if KINDLYDB_URL is not set.
    pub fn from_env() -> Result<Self, DbError> {
        let url = env::var("KINDLYDB_URL").map_err(|_| DbError::MissingUrl)?;
        Ok(Self::new(&url))
    }

    // ========================================================================
    // User Operations
    // ========================================================================

    /// Create a new user
    ///
    /// # Arguments
    ///
    /// * `user` - User data (id field is ignored, assigned by server)
    ///
    /// # Returns
    ///
    /// The assigned user ID.
    ///
    /// # Errors
    ///
    /// - `DbError::AlreadyExists` if email_hash already exists
    /// - `DbError::ConnectionFailed` on network error
    pub async fn create_user(&self, user: &User) -> Result<u64, DbError> {
        let url = format!("{}/users", self.base_url);

        let response = self.client.post(&url).json(user).send().await?;

        match response.status().as_u16() {
            200 | 201 => {
                let result: CreateUserResponse = response.json().await?;
                Ok(result.id)
            }
            409 => Err(DbError::AlreadyExists),
            status => Err(DbError::DatabaseError(format!(
                "Unexpected status {}: {}",
                status,
                response.text().await.unwrap_or_default()
            ))),
        }
    }

    /// Find user by email hash
    ///
    /// # Arguments
    ///
    /// * `email_hash` - BLAKE3 hash of email address
    ///
    /// # Returns
    ///
    /// `Some(User)` if found, `None` if not.
    pub async fn get_user_by_email_hash(&self, email_hash: u64) -> Result<Option<User>, DbError> {
        let url = format!("{}/users?email_hash={}", self.base_url, email_hash);

        let response = self.client.get(&url).send().await?;

        match response.status().as_u16() {
            200 => {
                let user: User = response.json().await?;
                Ok(Some(user))
            }
            404 => Ok(None),
            status => Err(DbError::DatabaseError(format!(
                "Unexpected status {}: {}",
                status,
                response.text().await.unwrap_or_default()
            ))),
        }
    }

    /// Get user by ID
    ///
    /// # Arguments
    ///
    /// * `id` - User ID
    ///
    /// # Returns
    ///
    /// `Some(User)` if found, `None` if not.
    pub async fn get_user_by_id(&self, id: u64) -> Result<Option<User>, DbError> {
        let url = format!("{}/users/{}", self.base_url, id);

        let response = self.client.get(&url).send().await?;

        match response.status().as_u16() {
            200 => {
                let user: User = response.json().await?;
                Ok(Some(user))
            }
            404 => Ok(None),
            status => Err(DbError::DatabaseError(format!(
                "Unexpected status {}: {}",
                status,
                response.text().await.unwrap_or_default()
            ))),
        }
    }

    /// Update an existing user
    ///
    /// # Arguments
    ///
    /// * `user` - Complete user data (must include valid id)
    ///
    /// # Errors
    ///
    /// - `DbError::NotFound` if user doesn't exist
    pub async fn update_user(&self, user: &User) -> Result<(), DbError> {
        let url = format!("{}/users/{}", self.base_url, user.id);

        let response = self.client.put(&url).json(user).send().await?;

        match response.status().as_u16() {
            200 | 204 => Ok(()),
            404 => Err(DbError::NotFound),
            status => Err(DbError::DatabaseError(format!(
                "Unexpected status {}: {}",
                status,
                response.text().await.unwrap_or_default()
            ))),
        }
    }

    /// Mark user as verified and issue license
    ///
    /// Convenience method that updates verification status,
    /// clears the token, and sets the license key.
    ///
    /// # Arguments
    ///
    /// * `user_id` - User ID
    /// * `license_key` - Generated license key
    /// * `is_promo` - Whether issued during promotional period
    pub async fn set_verified(
        &self,
        user_id: u64,
        license_key: &str,
        is_promo: bool,
    ) -> Result<(), DbError> {
        // Get current user
        let mut user = self
            .get_user_by_id(user_id)
            .await?
            .ok_or(DbError::NotFound)?;

        // Update verification fields
        user.email_verified = true;
        user.verification_token = None;
        user.verification_expires_at = None;
        user.license_key = Some(license_key.to_string());
        user.is_promo = is_promo;
        user.updated_at = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        self.update_user(&user).await
    }

    // ========================================================================
    // Audit Operations (Q34 Compliance)
    // ========================================================================

    /// Log an audit entry
    ///
    /// The entry's `prev_hash` should be computed using `compute_audit_hash`
    /// with the previous entry's hash (or 0 for the first entry).
    ///
    /// # Arguments
    ///
    /// * `entry` - Audit entry (id field is ignored, assigned by server)
    pub async fn log_audit(&self, entry: &SignupAuditEntry) -> Result<(), DbError> {
        let url = format!("{}/audit", self.base_url);

        let response = self.client.post(&url).json(entry).send().await?;

        match response.status().as_u16() {
            200 | 201 => Ok(()),
            status => Err(DbError::DatabaseError(format!(
                "Unexpected status {}: {}",
                status,
                response.text().await.unwrap_or_default()
            ))),
        }
    }

    /// Get audit trail for a user
    ///
    /// Returns all audit entries in chronological order.
    ///
    /// # Arguments
    ///
    /// * `user_id` - User ID to get audit trail for
    pub async fn get_audit_trail(&self, user_id: u64) -> Result<Vec<SignupAuditEntry>, DbError> {
        let url = format!("{}/audit?user_id={}", self.base_url, user_id);

        let response = self.client.get(&url).send().await?;

        match response.status().as_u16() {
            200 => {
                let entries: Vec<SignupAuditEntry> = response.json().await?;
                Ok(entries)
            }
            status => Err(DbError::DatabaseError(format!(
                "Unexpected status {}: {}",
                status,
                response.text().await.unwrap_or_default()
            ))),
        }
    }
}

// ============================================================================
// Mock Client for Testing
// ============================================================================

/// In-memory mock storage for testing
struct MockStorage {
    users: HashMap<u64, User>,
    users_by_email_hash: HashMap<u64, u64>,
    audit_entries: Vec<SignupAuditEntry>,
    next_user_id: AtomicU64,
    next_audit_id: AtomicU64,
}

impl MockStorage {
    fn new() -> Self {
        Self {
            users: HashMap::new(),
            users_by_email_hash: HashMap::new(),
            audit_entries: Vec::new(),
            next_user_id: AtomicU64::new(1),
            next_audit_id: AtomicU64::new(1),
        }
    }
}

/// Mock KindlyDB client for testing
///
/// Stores all data in memory, no network calls.
/// Thread-safe for concurrent test execution.
#[derive(Clone)]
pub struct MockKindlyDbClient {
    storage: Arc<RwLock<MockStorage>>,
}

impl MockKindlyDbClient {
    /// Create a new mock client
    pub fn new() -> Self {
        Self {
            storage: Arc::new(RwLock::new(MockStorage::new())),
        }
    }

    /// Create a user in mock storage
    pub async fn create_user(&self, user: &User) -> Result<u64, DbError> {
        let mut storage = self.storage.write().await;

        // Check for duplicate email_hash
        if storage.users_by_email_hash.contains_key(&user.email_hash) {
            return Err(DbError::AlreadyExists);
        }

        // Assign ID
        let id = storage.next_user_id.fetch_add(1, Ordering::SeqCst);
        let mut user = user.clone();
        user.id = id;

        // Store
        storage.users_by_email_hash.insert(user.email_hash, id);
        storage.users.insert(id, user);

        Ok(id)
    }

    /// Find user by email hash in mock storage
    pub async fn get_user_by_email_hash(&self, email_hash: u64) -> Result<Option<User>, DbError> {
        let storage = self.storage.read().await;

        match storage.users_by_email_hash.get(&email_hash) {
            Some(&id) => Ok(storage.users.get(&id).cloned()),
            None => Ok(None),
        }
    }

    /// Get user by ID from mock storage
    pub async fn get_user_by_id(&self, id: u64) -> Result<Option<User>, DbError> {
        let storage = self.storage.read().await;
        Ok(storage.users.get(&id).cloned())
    }

    /// Update user in mock storage
    pub async fn update_user(&self, user: &User) -> Result<(), DbError> {
        let mut storage = self.storage.write().await;

        if !storage.users.contains_key(&user.id) {
            return Err(DbError::NotFound);
        }

        storage.users.insert(user.id, user.clone());
        Ok(())
    }

    /// Mark user as verified in mock storage
    pub async fn set_verified(
        &self,
        user_id: u64,
        license_key: &str,
        is_promo: bool,
    ) -> Result<(), DbError> {
        let mut storage = self.storage.write().await;

        let user = storage.users.get_mut(&user_id).ok_or(DbError::NotFound)?;

        user.email_verified = true;
        user.verification_token = None;
        user.verification_expires_at = None;
        user.license_key = Some(license_key.to_string());
        user.is_promo = is_promo;
        user.updated_at = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        Ok(())
    }

    /// Log audit entry in mock storage
    pub async fn log_audit(&self, entry: &SignupAuditEntry) -> Result<(), DbError> {
        let mut storage = self.storage.write().await;

        let id = storage.next_audit_id.fetch_add(1, Ordering::SeqCst);
        let mut entry = entry.clone();
        entry.id = id;

        storage.audit_entries.push(entry);
        Ok(())
    }

    /// Get audit trail from mock storage
    pub async fn get_audit_trail(&self, user_id: u64) -> Result<Vec<SignupAuditEntry>, DbError> {
        let storage = self.storage.read().await;

        let entries: Vec<SignupAuditEntry> = storage
            .audit_entries
            .iter()
            .filter(|e| e.user_id == user_id)
            .cloned()
            .collect();

        Ok(entries)
    }

    /// Get all users (test helper)
    pub async fn get_all_users(&self) -> Vec<User> {
        let storage = self.storage.read().await;
        storage.users.values().cloned().collect()
    }

    /// Get all audit entries (test helper)
    pub async fn get_all_audit_entries(&self) -> Vec<SignupAuditEntry> {
        let storage = self.storage.read().await;
        storage.audit_entries.clone()
    }

    /// Clear all data (test helper)
    pub async fn clear(&self) {
        let mut storage = self.storage.write().await;
        storage.users.clear();
        storage.users_by_email_hash.clear();
        storage.audit_entries.clear();
        storage.next_user_id = AtomicU64::new(1);
        storage.next_audit_id = AtomicU64::new(1);
    }
}

impl Default for MockKindlyDbClient {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_user() -> User {
        User {
            id: 0,
            email_hash: 12345678901234567890,
            email_encrypted: "encrypted_email_data".to_string(),
            email_verified: false,
            verification_token: Some("123456".to_string()),
            verification_expires_at: Some(1700000000),
            tier: 0,
            license_key: None,
            org_name: "Test Org".to_string(),
            is_promo: false,
            created_at: 1699999000,
            updated_at: 1699999000,
        }
    }

    #[tokio::test]
    async fn test_mock_create_user() {
        let client = MockKindlyDbClient::new();
        let user = create_test_user();

        let id = client.create_user(&user).await.unwrap();
        assert_eq!(id, 1);

        // Verify stored
        let stored = client.get_user_by_id(id).await.unwrap().unwrap();
        assert_eq!(stored.email_hash, user.email_hash);
        assert_eq!(stored.org_name, "Test Org");
    }

    #[tokio::test]
    async fn test_mock_duplicate_email_hash() {
        let client = MockKindlyDbClient::new();
        let user = create_test_user();

        client.create_user(&user).await.unwrap();

        // Try to create another with same email_hash
        let result = client.create_user(&user).await;
        assert!(matches!(result, Err(DbError::AlreadyExists)));
    }

    #[tokio::test]
    async fn test_mock_get_by_email_hash() {
        let client = MockKindlyDbClient::new();
        let user = create_test_user();

        let id = client.create_user(&user).await.unwrap();

        let found = client
            .get_user_by_email_hash(user.email_hash)
            .await
            .unwrap();
        assert!(found.is_some());
        assert_eq!(found.unwrap().id, id);

        // Non-existent hash
        let not_found = client.get_user_by_email_hash(9999999999).await.unwrap();
        assert!(not_found.is_none());
    }

    #[tokio::test]
    async fn test_mock_update_user() {
        let client = MockKindlyDbClient::new();
        let user = create_test_user();

        let id = client.create_user(&user).await.unwrap();

        // Update
        let mut updated = client.get_user_by_id(id).await.unwrap().unwrap();
        updated.org_name = "Updated Org".to_string();
        client.update_user(&updated).await.unwrap();

        // Verify
        let fetched = client.get_user_by_id(id).await.unwrap().unwrap();
        assert_eq!(fetched.org_name, "Updated Org");
    }

    #[tokio::test]
    async fn test_mock_update_nonexistent() {
        let client = MockKindlyDbClient::new();
        let mut user = create_test_user();
        user.id = 999;

        let result = client.update_user(&user).await;
        assert!(matches!(result, Err(DbError::NotFound)));
    }

    #[tokio::test]
    async fn test_mock_set_verified() {
        let client = MockKindlyDbClient::new();
        let user = create_test_user();

        let id = client.create_user(&user).await.unwrap();

        client
            .set_verified(id, "KDB-HOBBY-ABCD1234", true)
            .await
            .unwrap();

        let verified = client.get_user_by_id(id).await.unwrap().unwrap();
        assert!(verified.email_verified);
        assert!(verified.verification_token.is_none());
        assert_eq!(verified.license_key, Some("KDB-HOBBY-ABCD1234".to_string()));
        assert!(verified.is_promo);
    }

    #[tokio::test]
    async fn test_mock_audit_logging() {
        let client = MockKindlyDbClient::new();

        let entry = SignupAuditEntry {
            id: 0,
            user_id: 1,
            event_type: "SIGNUP".to_string(),
            ip_address: "192.168.1.1".to_string(),
            prev_hash: 0,
            timestamp: 1699999000,
        };

        client.log_audit(&entry).await.unwrap();

        let trail = client.get_audit_trail(1).await.unwrap();
        assert_eq!(trail.len(), 1);
        assert_eq!(trail[0].event_type, "SIGNUP");
    }

    #[tokio::test]
    async fn test_mock_audit_chain() {
        let client = MockKindlyDbClient::new();

        // First entry
        let entry1 = SignupAuditEntry {
            id: 0,
            user_id: 1,
            event_type: "SIGNUP".to_string(),
            ip_address: "192.168.1.1".to_string(),
            prev_hash: 0,
            timestamp: 1699999000,
        };

        let hash1 = compute_audit_hash(&entry1, 0);
        client.log_audit(&entry1).await.unwrap();

        // Second entry linked to first
        let entry2 = SignupAuditEntry {
            id: 0,
            user_id: 1,
            event_type: "VERIFIED".to_string(),
            ip_address: "192.168.1.1".to_string(),
            prev_hash: hash1,
            timestamp: 1699999100,
        };

        client.log_audit(&entry2).await.unwrap();

        let trail = client.get_audit_trail(1).await.unwrap();
        assert_eq!(trail.len(), 2);
        assert_eq!(trail[0].event_type, "SIGNUP");
        assert_eq!(trail[1].event_type, "VERIFIED");
        assert_eq!(trail[1].prev_hash, hash1);
    }

    #[tokio::test]
    async fn test_compute_audit_hash_deterministic() {
        let entry = SignupAuditEntry {
            id: 1,
            user_id: 42,
            event_type: "SIGNUP".to_string(),
            ip_address: "10.0.0.1".to_string(),
            prev_hash: 0,
            timestamp: 1699999999,
        };

        let hash1 = compute_audit_hash(&entry, 0);
        let hash2 = compute_audit_hash(&entry, 0);

        assert_eq!(hash1, hash2);

        // Different prev_hash produces different result
        let hash3 = compute_audit_hash(&entry, 12345);
        assert_ne!(hash1, hash3);
    }

    #[tokio::test]
    async fn test_mock_clear() {
        let client = MockKindlyDbClient::new();
        let user = create_test_user();

        client.create_user(&user).await.unwrap();
        assert_eq!(client.get_all_users().await.len(), 1);

        client.clear().await;
        assert_eq!(client.get_all_users().await.len(), 0);
    }
}
