//! Auto-generated Ed25519 public key for license verification
//!
//! Generated by: kindly-av1-keygen
//! DO NOT EDIT MANUALLY - regenerate with keygen tool
//!
//! This key is embedded in the kindly-av1 binary for offline
//! license signature verification.

/// Ed25519 public key for offline license verification (32 bytes)
///
/// Used to verify Ed25519 signatures on stored license files.
/// The corresponding private key is held by the activation server.
pub const ED25519_PUBLIC_KEY: [u8; 32] = [
    0xb5, 0xc5, 0xde, 0x38, 0xb5, 0x14, 0x3d, 0x7e, 
    0x8c, 0x77, 0x02, 0xf7, 0xae, 0x70, 0x46, 0x1c, 
    0x9e, 0xb6, 0x11, 0x68, 0x0b, 0x14, 0x93, 0xfb, 
    0x3f, 0x4b, 0xa0, 0x49, 0xff, 0xbc, 0xb1, 0x3a, 
];
