//! Email Configuration Management (Phase 4 Item 3)
//!
//! # Architecture
//!
//! **Purpose**: Load and validate SMTP configuration for email delivery
//!
//! **Configuration File**: smtp_config.toml (in project root or ~/.config/kindly_dedup/)
//!
//! **Supported Providers**:
//! - Gmail (smtp.gmail.com:587, STARTTLS)
//! - Outlook (smtp.office365.com:587, STARTTLS)
//! - Custom SMTP servers
//!
//! # Example Configuration
//!
//! ```toml
//! [smtp]
//! server = "smtp.gmail.com"
//! port = 587
//! username = "your-email@gmail.com"
//! password = "your-app-password"  # Use app-specific password, NOT your Gmail password
//! use_tls = true  # STARTTLS (port 587)
//!
//! [email]
//! from = "your-email@gmail.com"
//! from_name = "Kindly Dedup Compliance"
//! to = ["recipient@example.com", "compliance@company.com"]
//! subject = "Kindly Dedup - Enterprise Compliance Report"
//! ```
//!
//! # Security
//! - Passwords stored in plaintext config file (user responsibility to protect)
//! - Use app-specific passwords (Gmail, Outlook) instead of account passwords
//! - Config file should have 0600 permissions (user read/write only)

use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

/// SMTP server configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SmtpConfig {
    /// SMTP server hostname (e.g., smtp.gmail.com)
    pub server: String,

    /// SMTP server port (typically 587 for STARTTLS, 465 for TLS)
    pub port: u16,

    /// SMTP authentication username (typically email address)
    pub username: String,

    /// SMTP authentication password (use app-specific password)
    pub password: String,

    /// Use STARTTLS (true for port 587, false for plain or TLS on 465)
    #[serde(default = "default_use_tls")]
    pub use_tls: bool,
}

fn default_use_tls() -> bool {
    true
}

/// Email message configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmailConfig {
    /// Sender email address
    pub from: String,

    /// Sender display name (optional)
    #[serde(default)]
    pub from_name: Option<String>,

    /// Recipient email addresses
    pub to: Vec<String>,

    /// Email subject line
    pub subject: String,

    /// Email body template (plain text, will be wrapped with Byzantine branding)
    #[serde(default = "default_body")]
    pub body: String,
}

fn default_body() -> String {
    "Please find attached the Kindly Dedup Enterprise Compliance Report.\n\n\
     This report contains audit trail verification results and compliance status.\n\n\
     Generated by Kindly Dedup v2.0\n\
     https://dedup.kindly.software"
        .to_string()
}

/// Root configuration structure
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmailDeliveryConfig {
    pub smtp: SmtpConfig,
    pub email: EmailConfig,
}

impl EmailDeliveryConfig {
    /// Load configuration from file
    ///
    /// # Search Order
    /// 1. ./smtp_config.toml (current directory)
    /// 2. ~/.config/kindly_dedup/smtp_config.toml (user config)
    /// 3. /etc/kindly_dedup/smtp_config.toml (system config, Linux only)
    ///
    /// # Returns
    /// - Ok(config) on success
    /// - Err(String) if no config file found or parsing fails
    pub fn load() -> Result<Self, String> {
        let config_paths = Self::get_config_paths();

        for path in &config_paths {
            if path.exists() {
                return Self::load_from_file(path);
            }
        }

        Err(format!(
            "No SMTP configuration file found. Searched:\n  {}\n\n\
             Create smtp_config.toml with your SMTP settings (see docs/EMAIL_SETUP.md)",
            config_paths
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join("\n  ")
        ))
    }

    /// Load configuration from specific file
    pub fn load_from_file(path: &Path) -> Result<Self, String> {
        let content = fs::read_to_string(path).map_err(|e| format!("Failed to read config file: {}", e))?;

        let config: EmailDeliveryConfig =
            toml::from_str(&content).map_err(|e| format!("Failed to parse config file: {}", e))?;

        // Validate configuration
        config.validate()?;

        Ok(config)
    }

    /// Save configuration to file (for testing)
    #[allow(dead_code)]
    pub fn save_to_file(&self, path: &Path) -> Result<(), String> {
        let content = toml::to_string_pretty(self).map_err(|e| format!("Failed to serialize config: {}", e))?;

        fs::write(path, content).map_err(|e| format!("Failed to write config file: {}", e))?;

        Ok(())
    }

    /// Get config file search paths
    fn get_config_paths() -> Vec<PathBuf> {
        let mut paths = Vec::new();

        // 1. Current directory
        paths.push(PathBuf::from("./smtp_config.toml"));

        // 2. User config directory (~/.config/kindly_dedup/)
        if let Some(config_dir) = dirs::config_dir() {
            paths.push(config_dir.join("kindly_dedup/smtp_config.toml"));
        }

        // 3. System config directory (Linux only)
        #[cfg(target_os = "linux")]
        paths.push(PathBuf::from("/etc/kindly_dedup/smtp_config.toml"));

        paths
    }

    /// Validate configuration
    fn validate(&self) -> Result<(), String> {
        // Validate SMTP server
        if self.smtp.server.is_empty() {
            return Err("SMTP server hostname is empty".to_string());
        }

        if self.smtp.port == 0 {
            return Err("SMTP port is 0 (invalid)".to_string());
        }

        if self.smtp.username.is_empty() {
            return Err("SMTP username is empty".to_string());
        }

        if self.smtp.password.is_empty() {
            return Err("SMTP password is empty".to_string());
        }

        // Validate email config
        if self.email.from.is_empty() {
            return Err("Sender email address is empty".to_string());
        }

        if self.email.to.is_empty() {
            return Err("No recipient email addresses specified".to_string());
        }

        if self.email.subject.is_empty() {
            return Err("Email subject is empty".to_string());
        }

        // Basic email address validation (simple check)
        if !self.email.from.contains('@') {
            return Err(format!("Invalid sender email address: {}", self.email.from));
        }

        for addr in &self.email.to {
            if !addr.contains('@') {
                return Err(format!("Invalid recipient email address: {}", addr));
            }
        }

        Ok(())
    }
}

/// Preset configurations for common providers
impl EmailDeliveryConfig {
    /// Gmail preset (requires app-specific password)
    ///
    /// # Setup
    /// 1. Enable 2FA on Gmail account
    /// 2. Generate app-specific password: https://myaccount.google.com/apppasswords
    /// 3. Use app password in config (NOT your Gmail password)
    #[allow(dead_code)]
    pub fn gmail_preset(email: &str, app_password: &str, recipients: Vec<String>) -> Self {
        Self {
            smtp: SmtpConfig {
                server: "smtp.gmail.com".to_string(),
                port: 587,
                username: email.to_string(),
                password: app_password.to_string(),
                use_tls: true,
            },
            email: EmailConfig {
                from: email.to_string(),
                from_name: Some("Kindly Dedup Compliance".to_string()),
                to: recipients,
                subject: "Kindly Dedup - Enterprise Compliance Report".to_string(),
                body: default_body(),
            },
        }
    }

    /// Outlook/Office 365 preset
    #[allow(dead_code)]
    pub fn outlook_preset(email: &str, password: &str, recipients: Vec<String>) -> Self {
        Self {
            smtp: SmtpConfig {
                server: "smtp.office365.com".to_string(),
                port: 587,
                username: email.to_string(),
                password: password.to_string(),
                use_tls: true,
            },
            email: EmailConfig {
                from: email.to_string(),
                from_name: Some("Kindly Dedup Compliance".to_string()),
                to: recipients,
                subject: "Kindly Dedup - Enterprise Compliance Report".to_string(),
                body: default_body(),
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_config_serialization() {
        let config = EmailDeliveryConfig {
            smtp: SmtpConfig {
                server: "smtp.example.com".to_string(),
                port: 587,
                username: "user@example.com".to_string(),
                password: "secret123".to_string(),
                use_tls: true,
            },
            email: EmailConfig {
                from: "sender@example.com".to_string(),
                from_name: Some("Test Sender".to_string()),
                to: vec!["recipient@example.com".to_string()],
                subject: "Test Subject".to_string(),
                body: "Test body".to_string(),
            },
        };

        let toml_str = toml::to_string(&config).unwrap();
        assert!(toml_str.contains("smtp.example.com"));
        assert!(toml_str.contains("user@example.com"));
    }

    #[test]
    fn test_config_deserialization() {
        let toml_str = r#"
            [smtp]
            server = "smtp.gmail.com"
            port = 587
            username = "test@gmail.com"
            password = "app-password"
            use_tls = true

            [email]
            from = "test@gmail.com"
            from_name = "Test User"
            to = ["recipient@example.com"]
            subject = "Test Subject"
            body = "Test body"
        "#;

        let config: EmailDeliveryConfig = toml::from_str(toml_str).unwrap();
        assert_eq!(config.smtp.server, "smtp.gmail.com");
        assert_eq!(config.smtp.port, 587);
        assert_eq!(config.email.to.len(), 1);
    }

    #[test]
    fn test_validation() {
        let valid_config = EmailDeliveryConfig {
            smtp: SmtpConfig {
                server: "smtp.example.com".to_string(),
                port: 587,
                username: "user@example.com".to_string(),
                password: "password".to_string(),
                use_tls: true,
            },
            email: EmailConfig {
                from: "sender@example.com".to_string(),
                from_name: None,
                to: vec!["recipient@example.com".to_string()],
                subject: "Subject".to_string(),
                body: "Body".to_string(),
            },
        };

        assert!(valid_config.validate().is_ok());

        // Test invalid email
        let mut invalid_config = valid_config.clone();
        invalid_config.email.from = "invalid-email".to_string();
        assert!(invalid_config.validate().is_err());

        // Test empty recipients
        let mut empty_recipients = valid_config.clone();
        empty_recipients.email.to.clear();
        assert!(empty_recipients.validate().is_err());
    }

    #[test]
    fn test_load_save() {
        let temp_dir = TempDir::new().unwrap();
        let config_path = temp_dir.path().join("test_smtp_config.toml");

        let config = EmailDeliveryConfig {
            smtp: SmtpConfig {
                server: "smtp.test.com".to_string(),
                port: 587,
                username: "test@test.com".to_string(),
                password: "test123".to_string(),
                use_tls: true,
            },
            email: EmailConfig {
                from: "test@test.com".to_string(),
                from_name: Some("Test".to_string()),
                to: vec!["recipient@test.com".to_string()],
                subject: "Test".to_string(),
                body: "Test body".to_string(),
            },
        };

        // Save
        config.save_to_file(&config_path).unwrap();
        assert!(config_path.exists());

        // Load
        let loaded_config = EmailDeliveryConfig::load_from_file(&config_path).unwrap();
        assert_eq!(loaded_config.smtp.server, "smtp.test.com");
        assert_eq!(loaded_config.email.from, "test@test.com");
    }

    #[test]
    fn test_gmail_preset() {
        let config = EmailDeliveryConfig::gmail_preset(
            "test@gmail.com",
            "app-password",
            vec!["recipient@example.com".to_string()],
        );

        assert_eq!(config.smtp.server, "smtp.gmail.com");
        assert_eq!(config.smtp.port, 587);
        assert!(config.smtp.use_tls);
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_outlook_preset() {
        let config = EmailDeliveryConfig::outlook_preset(
            "test@outlook.com",
            "password",
            vec!["recipient@example.com".to_string()],
        );

        assert_eq!(config.smtp.server, "smtp.office365.com");
        assert_eq!(config.smtp.port, 587);
        assert!(config.smtp.use_tls);
        assert!(config.validate().is_ok());
    }
}
